export const PLAYER_STATE = {
    IDLE: 'idle',
    MOVING_TO_TREE: 'moving_to_tree',
    CHOPPING: 'chopping',
    MOVING_TO_LOGS: 'moving_to_logs',
    HARVESTING_LOGS: 'harvesting_logs',
    MOVING_TO_BUSHES: 'moving_to_bushes',
    HARVESTING_BUSHES: 'harvesting_bushes',
    MOVING_TO_FLOWERS: 'moving_to_flowers',
    HARVESTING_FLOWERS: 'harvesting_flowers',
    SEARCHING_FOR_GATHERABLE: 'searching_for_gatherable',
    WANDERING_TO_GATHER: 'wandering_to_gather',
    SEARCHING_FOR_TREE: 'searching_for_tree',
    FOLLOWING: 'following',
};